#Asked AI to make me this list
question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "Bananas are berries, but strawberries are not.", "answer": "True"},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer.", "answer": "True"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "There are more stars in the universe than grains of sand on Earth.", "answer": "True"},
    {"text": "Water boils at 100°C everywhere on Earth.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "Goldfish only have a memory span of three seconds.", "answer": "False"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "Humans share 50% of their DNA with bananas.", "answer": "True"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "Mount Everest is the closest point on Earth to the moon.", "answer": "False"},
    {"text": "Penguins can walk as fast as they can swim.", "answer": "False"},
    {"text": "Coca-Cola was originally green.", "answer": "False"},
    {"text": "Wombat poop is cube-shaped.", "answer": "True"}
]
